2022-09-11 18:01:54.984 [main] WARN  o.s.b.w.s.c.AnnotationConfigServletWebServerApplicationContext - Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.BeanDefinitionStoreException: Failed to parse configuration class [com.fosss.eduorder.OrderApplication]; nested exception is java.io.FileNotFoundException: class path resource [org/springframework/security/core/userdetails/UserDetailsService.class] cannot be opened because it does not exist
2022-09-11 18:02:03.457 [main] WARN  o.s.b.w.s.c.AnnotationConfigServletWebServerApplicationContext - Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.BeanDefinitionStoreException: Failed to parse configuration class [com.fosss.eduservice.EduApplication]; nested exception is java.io.FileNotFoundException: class path resource [org/springframework/security/core/userdetails/UserDetailsService.class] cannot be opened because it does not exist
2022-09-11 18:03:22.825 [main] WARN  o.s.b.w.s.c.AnnotationConfigServletWebServerApplicationContext - Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.BeanDefinitionStoreException: Failed to parse configuration class [com.fosss.edustatistics.StaApplication]; nested exception is java.io.FileNotFoundException: class path resource [org/springframework/security/core/userdetails/UserDetailsService.class] cannot be opened because it does not exist
2022-09-11 18:04:16.232 [main] WARN  o.s.b.w.s.c.AnnotationConfigServletWebServerApplicationContext - Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.BeanDefinitionStoreException: Failed to parse configuration class [com.fosss.edustatistics.StaApplication]; nested exception is java.io.FileNotFoundException: class path resource [org/springframework/security/core/userdetails/UserDetailsService.class] cannot be opened because it does not exist
2022-09-11 18:05:33.571 [main] WARN  o.s.b.w.s.c.AnnotationConfigServletWebServerApplicationContext - Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.BeanDefinitionStoreException: Failed to read candidate component class: file [F:\Java\Maven\apache-maven-3.6.3\mvn_resp\org\springframework\boot\spring-boot-starter-parent\2.2.1.RELEASE\target\classes\com\fosss\canal\client\CanalClient.class]; nested exception is org.springframework.beans.factory.CannotLoadBeanClassException: Error loading class [com.fosss.gateway.filter.AuthGlobalFilter] for bean with name 'authGlobalFilter' defined in file [F:\Java\Maven\apache-maven-3.6.3\mvn_resp\org\springframework\boot\spring-boot-starter-parent\2.2.1.RELEASE\target\classes\com\fosss\gateway\filter\AuthGlobalFilter.class]: problem with class file or dependent class; nested exception is java.lang.NoClassDefFoundError: org/springframework/cloud/gateway/filter/GlobalFilter
2022-09-11 18:05:53.518 [main] WARN  com.netflix.config.sources.URLConfigurationSource - No URLs will be polled as dynamic configuration sources.
2022-09-11 18:05:53.521 [main] WARN  com.netflix.config.sources.URLConfigurationSource - No URLs will be polled as dynamic configuration sources.
2022-09-11 18:06:02.922 [main] WARN  o.s.b.w.s.c.AnnotationConfigServletWebServerApplicationContext - Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.BeanDefinitionStoreException: Failed to parse configuration class [com.fosss.edumsm.MsmApplication]; nested exception is java.io.FileNotFoundException: class path resource [org/springframework/security/core/userdetails/UserDetailsService.class] cannot be opened because it does not exist
2022-09-11 18:07:00.789 [main] WARN  o.s.b.w.s.c.AnnotationConfigServletWebServerApplicationContext - Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.BeanDefinitionStoreException: Failed to read candidate component class: file [F:\Java\Maven\apache-maven-3.6.3\mvn_resp\org\springframework\boot\spring-boot-starter-parent\2.2.1.RELEASE\target\classes\com\fosss\canal\client\CanalClient.class]; nested exception is org.springframework.beans.factory.CannotLoadBeanClassException: Error loading class [com.fosss.gateway.filter.AuthGlobalFilter] for bean with name 'authGlobalFilter' defined in file [F:\Java\Maven\apache-maven-3.6.3\mvn_resp\org\springframework\boot\spring-boot-starter-parent\2.2.1.RELEASE\target\classes\com\fosss\gateway\filter\AuthGlobalFilter.class]: problem with class file or dependent class; nested exception is java.lang.NoClassDefFoundError: org/springframework/cloud/gateway/filter/GlobalFilter
2022-09-11 18:08:06.816 [main] WARN  o.s.b.w.s.c.AnnotationConfigServletWebServerApplicationContext - Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.BeanDefinitionStoreException: Failed to read candidate component class: file [F:\Java\Maven\apache-maven-3.6.3\mvn_resp\org\springframework\boot\spring-boot-starter-parent\2.2.1.RELEASE\target\classes\com\fosss\canal\client\CanalClient.class]; nested exception is org.springframework.beans.factory.CannotLoadBeanClassException: Error loading class [com.fosss.gateway.filter.AuthGlobalFilter] for bean with name 'authGlobalFilter' defined in file [F:\Java\Maven\apache-maven-3.6.3\mvn_resp\org\springframework\boot\spring-boot-starter-parent\2.2.1.RELEASE\target\classes\com\fosss\gateway\filter\AuthGlobalFilter.class]: problem with class file or dependent class; nested exception is java.lang.NoClassDefFoundError: org/springframework/cloud/gateway/filter/GlobalFilter
2022-09-11 18:13:00.281 [main] WARN  o.s.b.w.s.c.AnnotationConfigServletWebServerApplicationContext - Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.BeanDefinitionStoreException: Failed to read candidate component class: file [F:\Java\Maven\apache-maven-3.6.3\mvn_resp\org\springframework\boot\spring-boot-starter-parent\2.2.1.RELEASE\target\classes\com\fosss\canal\client\CanalClient.class]; nested exception is org.springframework.beans.factory.CannotLoadBeanClassException: Error loading class [com.fosss.gateway.filter.AuthGlobalFilter] for bean with name 'authGlobalFilter' defined in file [F:\Java\Maven\apache-maven-3.6.3\mvn_resp\org\springframework\boot\spring-boot-starter-parent\2.2.1.RELEASE\target\classes\com\fosss\gateway\filter\AuthGlobalFilter.class]: problem with class file or dependent class; nested exception is java.lang.NoClassDefFoundError: org/springframework/cloud/gateway/filter/GlobalFilter
2022-09-11 18:16:20.237 [main] WARN  o.s.b.w.s.c.AnnotationConfigServletWebServerApplicationContext - Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.BeanDefinitionStoreException: Failed to read candidate component class: file [F:\Java\Maven\apache-maven-3.6.3\mvn_resp\org\springframework\boot\spring-boot-starter-parent\2.2.1.RELEASE\target\classes\com\fosss\canal\client\CanalClient.class]; nested exception is org.springframework.beans.factory.CannotLoadBeanClassException: Error loading class [com.fosss.gateway.filter.AuthGlobalFilter] for bean with name 'authGlobalFilter' defined in file [F:\Java\Maven\apache-maven-3.6.3\mvn_resp\org\springframework\boot\spring-boot-starter-parent\2.2.1.RELEASE\target\classes\com\fosss\gateway\filter\AuthGlobalFilter.class]: problem with class file or dependent class; nested exception is java.lang.NoClassDefFoundError: org/springframework/cloud/gateway/filter/GlobalFilter
2022-09-11 18:34:59.196 [main] WARN  c.a.cloud.nacos.client.NacosPropertySourceLocator - no instance of config service found, can't load config from nacos
2022-09-11 18:35:02.332 [main] WARN  com.netflix.config.sources.URLConfigurationSource - No URLs will be polled as dynamic configuration sources.
2022-09-11 18:35:02.336 [main] WARN  com.netflix.config.sources.URLConfigurationSource - No URLs will be polled as dynamic configuration sources.
2022-09-11 18:43:37.295 [main] WARN  com.netflix.config.sources.URLConfigurationSource - No URLs will be polled as dynamic configuration sources.
2022-09-11 18:43:37.300 [main] WARN  com.netflix.config.sources.URLConfigurationSource - No URLs will be polled as dynamic configuration sources.
2022-09-11 18:44:33.540 [main] WARN  com.netflix.config.sources.URLConfigurationSource - No URLs will be polled as dynamic configuration sources.
2022-09-11 18:44:33.544 [main] WARN  com.netflix.config.sources.URLConfigurationSource - No URLs will be polled as dynamic configuration sources.
2022-09-11 18:59:42.389 [main] WARN  com.netflix.config.sources.URLConfigurationSource - No URLs will be polled as dynamic configuration sources.
2022-09-11 18:59:42.392 [main] WARN  com.netflix.config.sources.URLConfigurationSource - No URLs will be polled as dynamic configuration sources.
2022-09-11 21:15:57.965 [lettuce-nioEventLoop-4-2] WARN  io.lettuce.core.protocol.ConnectionWatchdog - Cannot reconnect to [192.168.40.128:6379]: Connection refused: no further information: /192.168.40.128:6379
2022-09-11 21:16:18.166 [lettuce-nioEventLoop-4-4] WARN  io.lettuce.core.protocol.ConnectionWatchdog - Cannot reconnect to [192.168.40.128:6379]: connection timed out: /192.168.40.128:6379
2022-09-11 21:16:28.263 [lettuce-nioEventLoop-4-5] WARN  io.lettuce.core.protocol.ConnectionWatchdog - Cannot reconnect to [192.168.40.128:6379]: connection timed out: /192.168.40.128:6379
2022-09-11 21:16:38.355 [lettuce-nioEventLoop-4-6] WARN  io.lettuce.core.protocol.ConnectionWatchdog - Cannot reconnect to [192.168.40.128:6379]: connection timed out: /192.168.40.128:6379
2022-09-11 21:16:48.451 [lettuce-nioEventLoop-4-7] WARN  io.lettuce.core.protocol.ConnectionWatchdog - Cannot reconnect to [192.168.40.128:6379]: connection timed out: /192.168.40.128:6379
2022-09-11 21:16:58.558 [lettuce-nioEventLoop-4-8] WARN  io.lettuce.core.protocol.ConnectionWatchdog - Cannot reconnect to [192.168.40.128:6379]: connection timed out: /192.168.40.128:6379
2022-09-11 21:17:08.749 [lettuce-nioEventLoop-4-9] WARN  io.lettuce.core.protocol.ConnectionWatchdog - Cannot reconnect to [192.168.40.128:6379]: connection timed out: /192.168.40.128:6379
2022-09-11 21:17:19.054 [lettuce-nioEventLoop-4-10] WARN  io.lettuce.core.protocol.ConnectionWatchdog - Cannot reconnect to [192.168.40.128:6379]: connection timed out: /192.168.40.128:6379
2022-09-11 21:17:29.661 [lettuce-nioEventLoop-4-11] WARN  io.lettuce.core.protocol.ConnectionWatchdog - Cannot reconnect to [192.168.40.128:6379]: connection timed out: /192.168.40.128:6379
2022-09-11 21:17:40.761 [lettuce-nioEventLoop-4-12] WARN  io.lettuce.core.protocol.ConnectionWatchdog - Cannot reconnect to [192.168.40.128:6379]: connection timed out: /192.168.40.128:6379
2022-09-11 21:17:52.858 [lettuce-nioEventLoop-4-1] WARN  io.lettuce.core.protocol.ConnectionWatchdog - Cannot reconnect to [192.168.40.128:6379]: connection timed out: /192.168.40.128:6379
2022-09-11 21:18:07.074 [lettuce-nioEventLoop-4-2] WARN  io.lettuce.core.protocol.ConnectionWatchdog - Cannot reconnect to [192.168.40.128:6379]: connection timed out: /192.168.40.128:6379
2022-09-11 21:18:25.364 [lettuce-nioEventLoop-4-3] WARN  io.lettuce.core.protocol.ConnectionWatchdog - Cannot reconnect to [192.168.40.128:6379]: connection timed out: /192.168.40.128:6379
2022-09-11 21:18:51.862 [lettuce-nioEventLoop-4-4] WARN  io.lettuce.core.protocol.ConnectionWatchdog - Cannot reconnect to [192.168.40.128:6379]: connection timed out: /192.168.40.128:6379
2022-09-11 21:19:31.962 [lettuce-nioEventLoop-4-5] WARN  io.lettuce.core.protocol.ConnectionWatchdog - Cannot reconnect to [192.168.40.128:6379]: connection timed out: /192.168.40.128:6379
2022-09-11 21:20:12.057 [lettuce-nioEventLoop-4-6] WARN  io.lettuce.core.protocol.ConnectionWatchdog - Cannot reconnect to [192.168.40.128:6379]: connection timed out: /192.168.40.128:6379
2022-09-11 21:20:52.154 [lettuce-nioEventLoop-4-7] WARN  io.lettuce.core.protocol.ConnectionWatchdog - Cannot reconnect to [192.168.40.128:6379]: connection timed out: /192.168.40.128:6379
2022-09-11 21:21:32.259 [lettuce-nioEventLoop-4-8] WARN  io.lettuce.core.protocol.ConnectionWatchdog - Cannot reconnect to [192.168.40.128:6379]: connection timed out: /192.168.40.128:6379
2022-09-11 21:22:12.352 [lettuce-nioEventLoop-4-9] WARN  io.lettuce.core.protocol.ConnectionWatchdog - Cannot reconnect to [192.168.40.128:6379]: connection timed out: /192.168.40.128:6379
2022-09-11 21:22:52.450 [lettuce-nioEventLoop-4-10] WARN  io.lettuce.core.protocol.ConnectionWatchdog - Cannot reconnect to [192.168.40.128:6379]: connection timed out: /192.168.40.128:6379
2022-09-11 21:23:32.560 [lettuce-nioEventLoop-4-11] WARN  io.lettuce.core.protocol.ConnectionWatchdog - Cannot reconnect to [192.168.40.128:6379]: connection timed out: /192.168.40.128:6379
2022-09-11 21:24:12.664 [lettuce-nioEventLoop-4-12] WARN  io.lettuce.core.protocol.ConnectionWatchdog - Cannot reconnect to [192.168.40.128:6379]: connection timed out: /192.168.40.128:6379
2022-09-11 21:24:52.758 [lettuce-nioEventLoop-4-1] WARN  io.lettuce.core.protocol.ConnectionWatchdog - Cannot reconnect to [192.168.40.128:6379]: connection timed out: /192.168.40.128:6379
2022-09-11 21:25:32.861 [lettuce-nioEventLoop-4-2] WARN  io.lettuce.core.protocol.ConnectionWatchdog - Cannot reconnect to [192.168.40.128:6379]: connection timed out: /192.168.40.128:6379
2022-09-11 21:26:12.965 [lettuce-nioEventLoop-4-3] WARN  io.lettuce.core.protocol.ConnectionWatchdog - Cannot reconnect to [192.168.40.128:6379]: connection timed out: /192.168.40.128:6379
2022-09-11 21:26:53.068 [lettuce-nioEventLoop-4-4] WARN  io.lettuce.core.protocol.ConnectionWatchdog - Cannot reconnect to [192.168.40.128:6379]: connection timed out: /192.168.40.128:6379
2022-09-11 21:27:33.168 [lettuce-nioEventLoop-4-5] WARN  io.lettuce.core.protocol.ConnectionWatchdog - Cannot reconnect to [192.168.40.128:6379]: connection timed out: /192.168.40.128:6379
2022-09-11 21:28:13.261 [lettuce-nioEventLoop-4-6] WARN  io.lettuce.core.protocol.ConnectionWatchdog - Cannot reconnect to [192.168.40.128:6379]: connection timed out: /192.168.40.128:6379
2022-09-11 21:28:53.359 [lettuce-nioEventLoop-4-7] WARN  io.lettuce.core.protocol.ConnectionWatchdog - Cannot reconnect to [192.168.40.128:6379]: connection timed out: /192.168.40.128:6379
2022-09-11 21:29:33.455 [lettuce-nioEventLoop-4-8] WARN  io.lettuce.core.protocol.ConnectionWatchdog - Cannot reconnect to [192.168.40.128:6379]: connection timed out: /192.168.40.128:6379
2022-09-11 21:30:13.559 [lettuce-nioEventLoop-4-9] WARN  io.lettuce.core.protocol.ConnectionWatchdog - Cannot reconnect to [192.168.40.128:6379]: connection timed out: /192.168.40.128:6379
2022-09-11 21:30:53.657 [lettuce-nioEventLoop-4-10] WARN  io.lettuce.core.protocol.ConnectionWatchdog - Cannot reconnect to [192.168.40.128:6379]: connection timed out: /192.168.40.128:6379
2022-09-11 21:31:33.761 [lettuce-nioEventLoop-4-11] WARN  io.lettuce.core.protocol.ConnectionWatchdog - Cannot reconnect to [192.168.40.128:6379]: connection timed out: /192.168.40.128:6379
2022-09-11 21:32:13.859 [lettuce-nioEventLoop-4-12] WARN  io.lettuce.core.protocol.ConnectionWatchdog - Cannot reconnect to [192.168.40.128:6379]: connection timed out: /192.168.40.128:6379
2022-09-11 21:32:53.969 [lettuce-nioEventLoop-4-1] WARN  io.lettuce.core.protocol.ConnectionWatchdog - Cannot reconnect to [192.168.40.128:6379]: connection timed out: /192.168.40.128:6379
2022-09-11 21:33:34.058 [lettuce-nioEventLoop-4-2] WARN  io.lettuce.core.protocol.ConnectionWatchdog - Cannot reconnect to [192.168.40.128:6379]: connection timed out: /192.168.40.128:6379
2022-09-11 21:34:14.173 [lettuce-nioEventLoop-4-3] WARN  io.lettuce.core.protocol.ConnectionWatchdog - Cannot reconnect to [192.168.40.128:6379]: connection timed out: /192.168.40.128:6379
2022-09-11 21:34:54.258 [lettuce-nioEventLoop-4-4] WARN  io.lettuce.core.protocol.ConnectionWatchdog - Cannot reconnect to [192.168.40.128:6379]: connection timed out: /192.168.40.128:6379
2022-09-11 21:35:34.361 [lettuce-nioEventLoop-4-5] WARN  io.lettuce.core.protocol.ConnectionWatchdog - Cannot reconnect to [192.168.40.128:6379]: connection timed out: /192.168.40.128:6379
2022-09-11 21:36:14.450 [lettuce-nioEventLoop-4-6] WARN  io.lettuce.core.protocol.ConnectionWatchdog - Cannot reconnect to [192.168.40.128:6379]: connection timed out: /192.168.40.128:6379
2022-09-11 21:36:54.560 [lettuce-nioEventLoop-4-7] WARN  io.lettuce.core.protocol.ConnectionWatchdog - Cannot reconnect to [192.168.40.128:6379]: connection timed out: /192.168.40.128:6379
2022-09-11 21:37:34.667 [lettuce-nioEventLoop-4-8] WARN  io.lettuce.core.protocol.ConnectionWatchdog - Cannot reconnect to [192.168.40.128:6379]: connection timed out: /192.168.40.128:6379
2022-09-11 21:38:14.753 [lettuce-nioEventLoop-4-9] WARN  io.lettuce.core.protocol.ConnectionWatchdog - Cannot reconnect to [192.168.40.128:6379]: connection timed out: /192.168.40.128:6379
2022-09-11 21:38:54.852 [lettuce-nioEventLoop-4-10] WARN  io.lettuce.core.protocol.ConnectionWatchdog - Cannot reconnect to [192.168.40.128:6379]: connection timed out: /192.168.40.128:6379
2022-09-11 21:39:34.959 [lettuce-nioEventLoop-4-11] WARN  io.lettuce.core.protocol.ConnectionWatchdog - Cannot reconnect to [192.168.40.128:6379]: connection timed out: /192.168.40.128:6379
